name: run-code-coverage

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/coverage.yml"
      - "CMakeLists.txt"
      - "**.f90"
  pull_request:
    paths:
      - ".github/workflows/coverage.yml"
      - "CMakeLists.txt"
      - "**.f90"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  run-code-coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]
        version: [13]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v2.0.1
        with:
          cmake-version: '3.24.x'
            
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Install gcovr
        run: |
          pip --version
          pip install gcovr
      
      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake make
          cmake --version
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make
          make coverage

      - name: Get coverage percentage
        run: |
          pip install bs4
          echo "COVERAGE_PERCENTAGE="$(python ./tools/coverage_badge.py) >> $GITHUB_ENV
  
      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: fd7c07c046ecc92d92eaf7bdcb78c4b5
          filename: test.json # Use test.svg if you want to use the SVG mode.
          label: Coverage
          message: ${{ env.COVERAGE_PERCENTAGE }}%
          valColorRange: ${{ env.COVERAGE_PERCENTAGE }}
          maxColorRange: 100
          minColorRange: 0

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with: 
          path: './build/coverage/'
      
      - name: deploy to Github Pages
        uses: actions/deploy-pages@v2
        id: deployment
        
