name: run-fpm-build

on:
  push:
    paths:
      - ".github/workflows/fpm.yml"
      - "fpm.toml"
      - "**.f90"
  pull_request:
    paths:
      - ".github/workflows/fpm.yml"
      - "fpm.toml"
      - "**.f90"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false
  
jobs:
  build-and-test-fpm-debug:
    environment:
      name: github-pages
    name: Build and test in debug mode
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]
        version: [13]
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Set up GCC
      uses: actions/setup-gcc@v0
      with:
        gcc-version: latest
      
    - uses: fortran-lang/setup-fpm@v5
      id: setup-fortran
      with:
        fpm-version: "v0.9.0"
        compiler: ${{ matrix.compiler }}
        version: ${{ matrix.version }}

    - name: Compile
      run: |
        gfortran --version
        fpm build --profile debug

    - name: Test
      run: |
        gfortran --version
        fpm test --profile debug

  build-and-test-fpm-release:
    name: Build and test in release mode
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]
        version: [13]

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Set up GCC
      uses: actions/setup-gcc@v0
      with:
        gcc-version: latest
        
    - uses: fortran-lang/setup-fpm@v5
      id: setup-fortran
      with:
        fpm-version: "v0.9.0"
        compiler: ${{ matrix.compiler }}
        version: ${{ matrix.version }}

    - name: Compile
      run: |
        gfortran --version
        fpm build --profile release  --compiler 

    - name: Test
      run: |
        gfortran --version
        fpm test --profile release
